# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "admin_interface"
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joost Hietbrink"]
  s.date = "2012-03-28"
  s.description = "A Rails admin interface generator. Theme stolen from Redmine. Similar to web-app-theme but better ;)."
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/helpers/admin/base_helper.rb",
    "app/helpers/admin/country_select_helper.rb",
    "config/locales/en.yml",
    "lib/admin_interface.rb",
    "lib/admin_interface/engine.rb",
    "lib/admin_interface/version.rb",
    "lib/generators/admin_interface/SCAFFOLD_USAGE",
    "lib/generators/admin_interface/USAGE",
    "lib/generators/admin_interface/scaffold_generator.rb",
    "lib/generators/admin_interface/setup_generator.rb",
    "lib/generators/admin_interface/templates/scaffold/INSTALL",
    "lib/generators/admin_interface/templates/scaffold/controller.rb",
    "lib/generators/admin_interface/templates/scaffold/functional_test.rb",
    "lib/generators/admin_interface/templates/scaffold/helper.rb",
    "lib/generators/admin_interface/templates/scaffold/helper_test.rb",
    "lib/generators/admin_interface/templates/scaffold/layout.html.erb",
    "lib/generators/admin_interface/templates/scaffold/style.css",
    "lib/generators/admin_interface/templates/scaffold/view_edit.html.erb",
    "lib/generators/admin_interface/templates/scaffold/view_form_partial.html.erb",
    "lib/generators/admin_interface/templates/scaffold/view_index.html.erb",
    "lib/generators/admin_interface/templates/scaffold/view_list_partial.html.erb",
    "lib/generators/admin_interface/templates/scaffold/view_new.html.erb",
    "lib/generators/admin_interface/templates/scaffold/view_show.html.erb",
    "lib/generators/admin_interface/templates/setup/INSTALL",
    "lib/generators/admin_interface/templates/setup/controllers/base_controller.rb",
    "lib/generators/admin_interface/templates/setup/controllers/resource_controller.rb",
    "lib/generators/admin_interface/templates/setup/views/index.html.erb",
    "lib/generators/admin_interface/templates/setup/views/layout.html.erb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A Rails admin interface generator. Theme stolen from Redmine."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<admin_interface>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<geminabox>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<geminabox>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<geminabox>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<geminabox>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<geminabox>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0.12.4"])
      s.add_runtime_dependency(%q<ransack>, [">= 0"])
      s.add_runtime_dependency(%q<inherited_resources>, [">= 1.2.2"])
      s.add_runtime_dependency(%q<simple_form>, [">= 0"])
      s.add_runtime_dependency(%q<country_code_select>, [">= 0"])
      s.add_runtime_dependency(%q<dynamic_form>, [">= 0"])
    else
      s.add_dependency(%q<admin_interface>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<geminabox>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<geminabox>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<geminabox>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<geminabox>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<geminabox>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0.12.4"])
      s.add_dependency(%q<ransack>, [">= 0"])
      s.add_dependency(%q<inherited_resources>, [">= 1.2.2"])
      s.add_dependency(%q<simple_form>, [">= 0"])
      s.add_dependency(%q<country_code_select>, [">= 0"])
      s.add_dependency(%q<dynamic_form>, [">= 0"])
    end
  else
    s.add_dependency(%q<admin_interface>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<geminabox>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<geminabox>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<geminabox>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<geminabox>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<geminabox>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0.12.4"])
    s.add_dependency(%q<ransack>, [">= 0"])
    s.add_dependency(%q<inherited_resources>, [">= 1.2.2"])
    s.add_dependency(%q<simple_form>, [">= 0"])
    s.add_dependency(%q<country_code_select>, [">= 0"])
    s.add_dependency(%q<dynamic_form>, [">= 0"])
  end
end

